#!/bin/bash

SINGLE=false
SVNDIFFARGS=
while expr "$1" : - > /dev/null ; do
  case "$1" in
    -b) SVNDIFFARGS="-x -b "
        ;;
    -w) SVNDIFFARGS="-x -w "
        ;;
    --ignore-eol-style)
        SVNDIFFARGS="-x --ignore-eol-style"
        ;;
    -s) SINGLE=true
        ;;
    *) echo "$0: unrecognized option $1"
       exit 1
       ;;
  esac
  shift
done
      
if $SINGLE ; then
  if [ -z "$@" ] ; then
    FILES=`svn status | awk '/^[MAD]/ { print $NF }'`
  else
    FILES="$@"
  fi
  LONGEST=0
  for FILE in $FILES ; do
    if [ `expr $FILE : '.*'` -gt $LONGEST ] ; then
      LONGEST=`expr $FILE : '.*'`
    fi
  done
  for FILE in `echo $FILES | tr [:blank:] "\n" | sort` ; do
    svn diff $SVNDIFFARGS $FILE | \
      awk -v FILE=$FILE -v SIZE=$LONGEST '/^\+/ { plus++ }
                                          /^\-/ { minus++ }
                                          END {printf "%-*s\tadded %5d\tremoved %5d\ttotal %5d\n", SIZE, FILE, plus, minus, plus - minus }'
  done
else
  svn diff $SVNDIFFARGS $@ | awk '/^\+/ { plus++ } /^\-/ { minus++ } END {printf "added %5d\tremoved %5d\ttotal %5d\n", plus, minus, plus - minus }'
fi
