#!/bin/sh

TABWIDTH=8
PROGNAME=`basename $0`
TMPFILE=${TMPDIR:-/tmp}/$PROGNAME.$$
SILENT=0
NUMTOCOUNT=1
AWK=awk

case `uname -s` in
	SunOS)
		EXPAND=expand
		#EXPANDFLAG=-t
		EXPANDFLAG=-
		;;
	HP-UX|*)
		EXPAND="pr -t"
		EXPANDFLAG=-e
		;;
esac
USAGE="$PROGNAME [ -h ] [ -c count ] [ -s ] [ -{e|t} tab-width | -E ] [ file [ ... ] ]"

if set -- `getopt hc:Ee:st: $*` ; then
	true
else
	echo $USAGE
	exit 1
fi

while [ $1 != -- ] ; do
	case $1 in
		-h)	echo $USAGE
			echo
			echo "	-h	get this help"
			echo "	-c	print the lengths of the count longest lines"
			echo "	-s	silent mode - just print the line length"
			echo "	-e	expand tabs to tab-width spaces (default = 8)"
			echo "	-t	same as -e"
			echo "	-E	don't expand tabs to spaces"
			exit 1
			;;
		-c)	NUMTOCOUNT=$2
			shift 2
			;;
		-e|-t)
			TABWIDTH=$2
			shift 2
			;;
		-E)	EXPAND=cat
			EXPANDFLAG=
			TABWIDTH=
			shift
			;;
		-s)	SILENT=1
			shift
			;;
		*)	echo $PROGNAME: $1 is not a known option
			exit 1
			;;
	esac
done
if [ $1 = -- ] ; then
	shift
fi

if [ $# -eq 0 ] ; then
    cat > $TMPFILE
    FILELIST=$TMPFILE
else
    FILELIST="$*"
fi

for FILE in $FILELIST ; do
    $EXPAND ${EXPANDFLAG}$TABWIDTH $FILE | \
	$AWK '{ print length, NR, $0 }' | \
	sort -n | tail -$NUMTOCOUNT | \
	$AWK '{
	    if (silent == 0)
		{
		print "'$FILE'", $0
		}
	    else
		{
		print "'$FILE'" "\t" $1
		}
	    }' silent=$SILENT
done
rm -f $TMPFILE
