######################################################################
# Automatically generated by qmake (3.0) Fri Nov 30 11:03:43 2018
######################################################################

TEMPLATE = app
TARGET = multipleQueries
INCLUDEPATH += .
QT += sql

# Input
SOURCES += main.cpp
