#!/usr/bin/perl
foreach $option (@ARGV) {
    if ($option =~ /^-/) {
	push @sdiffOptions, $option;
	shift @ARGV;
    } else {
	last;
    }
}

foreach $filename (@ARGV) {
    open CVSSTATUS, "cvs status $filename|";
    while (<CVSSTATUS>) {
	chomp;
	if (/Status: (Locally Modified|.*)/) {
	    $verSubtraction = ($1 eq "Locally Modified") ? 0 : 1;
	} elsif (/Working revision:\s*([0-9.]+)/) {
	    $curVersion = $1;
	}
    }
    close CVSSTATUS;

    @curVersionParts = split /\./, $curVersion;
    @preVersionParts = @curVersionParts;

    $preVersionParts[-1] -= $verSubtraction;
    $preVersion = join ".", @preVersionParts;

    system("cvs update -r $preVersion -p $filename > /tmp/$filename.$preVersion");
    system("sdiff @sdiffOptions /tmp/$filename.$preVersion $filename");
}
