#!/bin/bash

PROG=`basename $0`
STAR="*"
WIDTH=${COLUMNS:-80}
SHOWDATE=false

function usage() {
cat <<-EOUSAGE
	$PROG -h
	$PROG [ -c char ] [ -d ] [ -w width ] [ string-to-display ]
	EOUSAGE
}

while getopts hc:dw: OPTION ; do
  case $OPTION in
    h) usage ; exit 0 ;;
    c) STAR=$OPTARG   ;;
    d) SHOWDATE=true  ;;
    w) WIDTH=$[$OPTARG + 0]
       if [ $WIDTH -eq 0 ] ; then WIDTH=80 ; fi
       ;;
  esac
done

shift $[$OPTIND - 1]

TEXT="$*"
if $SHOWDATE ; then
  TEXT="$(date) $TEXT"
fi

if [ -n "$TEXT" ] ; then
  echo -n "$TEXT "
else
  echo -n "$STAR"
fi
for (( WIDTH-- ; $WIDTH > "${#TEXT}" ; WIDTH=$WIDTH - ${#STAR} )) ; do
  echo -n "$STAR"
done
echo
