#!/bin/bash

PROG=`basename $0`
STAR="*"
WIDTH=80

SHOWDATE=false

function usage() {
cat <<EOUSAGE
$PROG -h
$PROG [ -c char ] [ -d ] [ -w width ] [ string-to-display ]
EOUSAGE
}

function stars() {
  local CNT=${1:-$STARLEN}
  local STARS

  while [ $CNT -gt 0 ] ; do
    STARS="${STARS}${STAR}"
    CNT=$[$CNT - 1]
  done

  echo "$STARS"
}

while getopts hc:dw: OPTION ; do
  case $OPTION in
    h) usage
       exit 0
       ;;
    c) STAR=$OPTARG
       ;;
    d) SHOWDATE=true
       ;;
    w) WIDTH=$[$OPTARG + 0]
       if [ $WIDTH -eq 0 ] ; then WIDTH=80 ; fi
       ;;
  esac
done

shift $[$OPTIND - 1]

TEXT="$*"
if $SHOWDATE ; then
  TEXT="$(date) $TEXT"
fi

TEXTLEN=$(echo -- $TEXT | wc -c)
STARLEN=$[$WIDTH - $TEXTLEN + 2]
MINLEN=$[$WIDTH / 4]

if [ $STARLEN -lt $MINLEN ] ; then
  echo $TEXT
  stars $[$WIDTH - 1]
else
  echo -n "$TEXT "
  stars
fi
