#!/bin/bash
#
# see the response from raphinesse @
# https://stackoverflow.com/questions/10622179/how-to-find-identify-large-files-commits-in-git-history

git rev-list --objects --all | \
   git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' | \
   awk '/^blob/ {print substr($0,6)}' | \
   sort --numeric-sort --key=2 | \
   cut --complement --characters=13-40 | \
   numfmt --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest

